### ISSUE TITLE
Not able to put in Recovery mode

### ISSUE THREAD

**Issue by harishkumarb-tw** [WeActStudio/Nano_TX2-Xavier_NX-CB#5]
The **lsusb** shows `Bus 001 Device 047: ID 0955:7e19 NVIDIA Corp. APX`. Even when trying to press the rec button and restart the board doesn't help in changing the mode to recovery.
We have 3 boards - Xavier NX and we cannot change it to Recovery in all of them.

**Comment by Greetrix** [comment]
Hi, when you see the NVIDIA Corp. APX, the core board is in recovery mode.
