### ISSUE TITLE
SD Card not detected even after device tree update

### ISSUE THREAD

**Issue by harishkumarb-tw** [WeActStudio/Nano_TX2-Xavier_NX-CB#6]
1. Installed base Tegra Image(Jetpack 5.0.2)
2. Updated the kernal Device Tree in EMMC

After reboot, the sdcard is not shown when I run `df -H`

**Comment by Greetrix** [comment]
Hi, our device-tree only support 4.x not. Jetpack 5.x will be updated later, please wait it.

**Comment by harishkumarb-tw** [comment]
> Hi, our device-tree only support 4.x now. Jetpack 5.x will be updated later, please wait it.

@Greetrix Are there any expected dates for the release of the device tree for Jetpack 5.x?
