### ISSUE TITLE
Booting from EMMC and not SD card

### ISSUE THREAD

**Issue by 2vin2vin** [WeActStudio/Nano_TX2-Xavier_NX-CB#7]
Hi, I have a Xavier board that I have flashed with Jetpack 4.6.3 and after following all the steps to migrate to SD card. When running the df -l command, I get the EMMC showing along with SD card also. Need help to get it to boot from SD card.

**Comment by harishkumarb-tw** [comment]
@2vin2vin I followed this, and it works pretty well for me. I used it to migrate roofs from EMMC to sd card and also to USB.
[Change Root File System to SD Card Directly](https://www.forecr.io/blogs/bsp-development/change-root-file-system-to-sd-card-directly)

**Comment by Greetrix** [comment]
@2vin2vin Hi, please follow all step in our user guide.
