### ISSUE TITLE
3d Model of the Carrier Board

### ISSUE THREAD

**Issue by Simon-Pokorny** [WeActStudio/Nano_TX2-Xavier_NX-CB#8]
Dear Sir or madam,

I was wondering if you might publish the 3d model of the carrierboard itself as well. 
I just found the 3d model of the case but to integrate the carrier board into my design i need the step file of the carrier board. 
Could you publish that as well? 

thank you & kind regards

**Comment by Greetrix** [comment]
Hi, Simon-Pokorny
Please contact the supplier which you bought the carrier board to get 3D model, and it is not a open source.
Thanks and Regards.
