### ISSUE TITLE
Veye and WeAct dtbs at the same time

### ISSUE THREAD

**Issue by vswdigitall** [WeActStudio/Nano_TX2-Xavier_NX-CB#9]
Hi, my name is Viktor.

I ordered many times your excellent boards form Ali.
And will order again.

All works on Nvidia Jetson NX l4t4.5.1. 
But now i need to install Veye camera sensor (http://wiki.veye.cc/index.php/VEYE_CS_Camera_for_Jetson_TX2) on Nvidia Jetson **Nano Emmc** l4t4.5.1 with **SD** card support.

Veye has own dtb with camera config.
How to use Veye and WeAct dtbs at the same time?

Can you help to solve it?

**Comment by vswdigitall** [comment]
I solve it. It was easy )

Decompiled Veye dtb to dts.
Then changed 1 line from disable to okay (red) and added 2 new lines (green)
And compile it back.
![photo1680448730](https://user-images.githubusercontent.com/48950231/229363042-0d5006e0-6a4f-4e55-9463-4295caef2864.jpeg)

Works.
Closed.

**Comment by Greetrix** [comment]
Hi Viktor,
Thanks for your sharing.
BR,
Greetrix
